-- =============================================================================
-- PruebaGF - Script de la base de datos
-- =============================================================================
-- Motor: PostgreSQL
-- Base:   PruebaGF
--
-- Este script crea la tabla "usuarios" usada por el backend Laravel de PruebaGF.
-- En el flujo normal del proyecto la tabla se crea con `php artisan migrate`;
-- este archivo se incluye como entregable del script de base de datos.
--
-- Uso:
--   psql -U root -d PruebaGF -f PruebaGF.sql
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Tabla: usuarios
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS usuarios (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identificacion    varchar(20)  NOT NULL,
    nombre_usuario    varchar(50)  NOT NULL,
    apellidos         varchar(100) NOT NULL,
    nombres           varchar(100) NOT NULL,
    fecha_nacimiento  date         NOT NULL,
    celular           varchar(20)  NOT NULL,
    telefono          varchar(20),
    correo_personal   varchar(150) NOT NULL,
    estado_civil      varchar(20)  NOT NULL,
    sexo              varchar(10)  NOT NULL,
    direccion         varchar(255),
    created_at        timestamp(0) without time zone,
    updated_at        timestamp(0) without time zone,

    CONSTRAINT usuarios_estado_civil_check
        CHECK (estado_civil IN ('soltero', 'casado', 'divorciado', 'viudo', 'union_libre')),
    CONSTRAINT usuarios_sexo_check
        CHECK (sexo IN ('masculino', 'femenino', 'otro'))
);

-- Llaves unicas
CREATE UNIQUE INDEX IF NOT EXISTS usuarios_identificacion_unique
    ON usuarios (identificacion);

CREATE UNIQUE INDEX IF NOT EXISTS usuarios_nombre_usuario_unique
    ON usuarios (nombre_usuario);

CREATE UNIQUE INDEX IF NOT EXISTS usuarios_correo_personal_unique
    ON usuarios (correo_personal);

-- -----------------------------------------------------------------------------
-- Datos de ejemplo (opcional)
-- -----------------------------------------------------------------------------
INSERT INTO usuarios (
    identificacion, nombre_usuario, apellidos, nombres, fecha_nacimiento,
    celular, telefono, correo_personal, estado_civil, sexo, direccion,
    created_at, updated_at
) VALUES
    ('1723456789', 'jgarcia',  'Garcia Lopez',  'Juan',       '1990-05-12', '0987654321', '022123456', 'juan@example.com',     'soltero',      'masculino', 'Av. Amazonas 123, Quito', now(), now()),
    ('1719876543', 'mperez',   'Perez Mendoza', 'Maria',      '1992-09-23', '0991234567', NULL,        'maria@example.com',    'casado',       'femenino',  'Av. 6 de Diciembre 456', now(), now()),
    ('1798765432', 'lvega',    'Vega Torres',   'Luis',       '1988-03-30', '0967891234', '023456789', 'luis@example.com',     'union_libre',  'masculino', 'Calle Bolivar 789',      now(), now())
ON CONFLICT DO NOTHING;